### ISSUE TITLE
[Feature]: Add support for providing allowed list along with banned list

### ISSUE THREAD

**Issue by yogeshkumar98103** [Iteo/architecture_linter#46]
### Problem

I am trying to enforce feature first approach in clean architecture. I want to enforce a check which disallows imports between features. Using banned_imports to achieve this is O(n^2). 

### Desired Solution

This can be done in O(n) if there is support for allowed_imports.

### On which platorm do you expect this solution?

All

**Comment by tomkad99** [comment]
Hi @yogeshkumar98103 !

Thank you for your insights here. That is really nice that you brings performance topic. 
Main idea for this project is "prohibiting X" than allowing for any X.

This is due to rule: "Everything which is not forbidden is allowed", that makes this library less potentially harmful for any project.
